theme: just-the-docs
title: BSCMSE 2023-2024 Senior Capstone Project homepage
permalink: /:categories/:title/
description: Bookmark this to keep an eye on the capstone project updates!

collections:
  project_developers:
    people: true
    output: true